image: alpine/latest
packages:
  - nodejs
  - npm
  - wget
oauth: pages.sr.ht/PAGES:RW
environment:
  repo: writing
  site: write.rog.gr
  hugo_version: "v0.111.3"
tasks:
- setup: |
   wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_Linux-64bit.tar.gz"
   wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_checksums.txt"
   calculated_sha=$(sha256sum "hugo_extended_${hugo_version}_Linux-64bit.tar.gz")
   expected_sha=$(grep "hugo_extended_${hugo_version}_Linux-64bit.tar.gz" "hugo_extended_${hugo_version}_checksums.txt")
   printf "calculated: %s\n  expected: %s" "$calculated_sha" "$expected_sha"
   [ "$calculated_sha" = "$expected_sha" ]
   tar xzf "hugo_extended_${hugo_version}_Linux-64bit.tar.gz"
   hugo env
   export PATH="$(pwd)/hugo:${PATH}"
- build: |
    cd ${repo}
    npm install
- package: |
    cd ${repo}
    npm run build
    tar -C public -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d ${site} site.tar.gz
