image: alpine/latest
packages:
  - nodejs
  - npm
  - hugo
oauth: pages.sr.ht/PAGES:RW
environment:
  repo: writing
  site: write.rog.gr
tasks:
- build: |
    cd ${repo}
    npm install
- package: |
    cd ${repo}
    npm run build
    tar -C public -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d ${site} site.tar.gz
