baseURL = ""
languageCode = "en-US"
defaultContentLanguage = 'en-us'

[languages]

[languages.es]
contentDir = "content/es"
title = 'Roger Steve Ruiz es un ingeniero de software'
description = "Ayudo a construir servicios digitales centrados en el usuario."
weight = 2

[languages.en-us]
contentDir = "content/en"
title = "Roger Steve Ruiz is a software engineer"
description = "I help build user-centered digital services."
weight = 1

[params]
AuthorName = "Roger Steve Ruiz"

[[params.social]]
Name = "Mastadon"
BaseURL = "https:/infosec.exchange/"
Handle = "@rogeruiz"

[[params.social]]
Name = "Twitter"
BaseURL = "https://twitter.com/"
Handle = "@rogeruiz"

[[params.social]]
Name = "sourcehut"
BaseURL = "https://git.sr.ht/"
Handle = "~rogeruiz"

[[params.social]]
Name = "GitHub"
BaseURL = "https://github.com/"
Handle = "@rogeruiz"

[[params.social]]
Name = "LinkedIn"
BaseURL = "https://linkedin.com/"
Handle = "in/rogeruiz"

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]

[markup.goldmark]

[markup.goldmark.extensions]
gfm = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[markup.highlight]
noClasses = false
