baseURL = "https://write.rog.gr/"
languageCode = "en-US"
defaultContentLanguage = 'en-us'

[languages]

[languages.es]
contentDir = "content/es"
title = 'Roger Ruiz es un ingeniero de software.'
weight = 2
[languages.es.params]
description = "Ayudo a construir servicios digitales centrados en el usuario."

[languages.en-us]
contentDir = "content/en"
title = "Roger Ruiz is a software engineer."
weight = 1
[languages.en-us.params]
description = "I help build user-centered digital services."

[params]
AuthorName = "Roger Ruiz"

[[params.social]]
Name = "Exercism"
BaseURL = "https://exercism.org/"
Handle = "profiles/rogeruiz"

[[params.social]]
Name = "CodeSignal"
BaseURL = "https://app.codesignal.com/"
Handle = "profiles/rogeruiz"

[[params.social]]
Name = "Mastadon"
BaseURL = "https:/infosec.exchange/"
Handle = "@rogeruiz"

[[params.social]]
Name = "Twitter"
BaseURL = "https://twitter.com/"
Handle = "@rogeruiz"

[[params.social]]
Name = "sourcehut"
BaseURL = "https://git.sr.ht/"
Handle = "~rogeruiz"

[[params.social]]
Name = "GitHub"
BaseURL = "https://github.com/"
Handle = "@rogeruiz"

[[params.social]]
Name = "LinkedIn"
BaseURL = "https://linkedin.com/"
Handle = "in/rogeruiz"

[[params.social]]
Name = "BuyMeACoffee"
BaseURL = "https://www.buymeacoffee.com/"
Handle = "rstrz"

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]

[markup.goldmark]

[markup.goldmark.extensions]
gfm = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false

[markup.highlight]
noClasses = false
