baseURL = ""
languageCode = "en-us"
title = "Roger Steve Ruiz is a software engineer"

[params]
AuthorName = "Roger Steve Ruiz"
[params.username]
Twitter = "@rogeruiz"
GitHub = "@rogeruiz"
Sourcehut = "~rogeruiz"
LinkedIn = "in/rogers.ruiz"
Mastadon = "@rogeruiz"

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xhtml = false
[markup.highlight]
style = "dracula"
